export enum LayerTypes {
  FEATURE = 'feature',
  MAP_IMAGE = 'map-image',
  CSV = 'csv',
  GEOJSON = 'geojson',
  GRAPHICS = 'graphics',
  GROUP = 'group',
  IMAGE = 'image',
  IMAGERY = 'imagery',
  IMAGERY_TILE = 'imagery-tile',
  MEDIA = 'media',
  OPEN_STREET_MAP = 'osm',
  RASTER = 'raster',
  STREAM = 'stream',
  TILE = 'tile',
  VECTOR_TILE = 'vector-tile',
  WEB_TILE = 'web-tile',
  WMS = 'wms',
  WMTS = 'wmts',
  UNKNOWN = 'unknown'
}
